### ISSUE TITLE
Can only respawn in current dimension in a bed. (v1.0.2 MC1.10.2 Forge-12.18.3.2254)

### ISSUE THREAD

**Issue by Pyromstr** [UpcraftLP/Respawn-Location-Picker#4]
If choose a respawn point in a dimension other than the one I died in I respawn at the correct co-ords, but I am not properly teleported into the dimension I chose. Instead, I stay in the dimension I died in. This often results in falling out of the sky or suffocation.

Additionally, choosing the world spawn option results in spawning close to the correct location, only underground!

Choosing a bed in the dimension of death works correctly.

I really hope there is a simple fix as this was going to be an important part of my modpack. This issue persists even after a clean install with only this mod.

**Comment by UpcraftLP** [comment]
Thanks for notifying me, I'll look into it ;)

**Comment by Pyromstr** [comment]
Great! I hope it made sense, I was struggling to put it in writing for some reason. 

If you need any more details on my end, just let me know :)

**Comment by UpcraftLP** [comment]
will be fixed in the next release, thanks for reporting :)
