### ISSUE TITLE
[Suggestion] Name the bed spawnpoints after the bed's color

### ISSUE THREAD

**Issue by phistoh** [UpcraftLP/Respawn-Location-Picker#5]
I think the title explains it: If the player sleeps in a green bed, the corresponding button should be labeled "green bed", if the player sleeps in a red bed, the button should be labeled "red bed" and so on.

I don't know if this is easy implementable but it would make it easier to organize the spawnpoints (without manually setting spawnpoints via command). And it would give colored beds a purpose besides aesthetics.

**Comment by UpcraftLP** [comment]
sounds good, I'll add a config option for that tho, so you can disable it later

**Comment by UpcraftLP** [comment]
done.
