### ISSUE TITLE
[1.12]-Server does not respond after clicking on "Bed"

### ISSUE THREAD

**Issue by ErdbeerbaerLP** [UpcraftLP/Respawn-Location-Picker#7]
No crash report, needed to kill the server to restart it.
It happened multiple times now

**Comment by UpcraftLP** [comment]
post your mc version, forge version, mod version and a recent fml log. (`/logs/fml-client-latest.log`)

**Comment by ErdbeerbaerLP** [comment]
1.12, Forge 14.23.4.2705, Respawn Location Picker 1.3.0

I dont have any log right now. And it also did not output anything...

**Comment by UpcraftLP** [comment]
well I need a log anyways
